### ISSUE TITLE
snappy 1.1

### ISSUE THREAD

**Issue by bokken** [dain/snappy#28]
The documentation page states "This compression code produces a byte-for-byte exact copy of the output created by the original C++ code..." That appears to be accurate for the 1.0.4 version of snappy. There are differences, however, with the 1.1 version of snappy. This can be seen by comparing output from snappy-java 1.1 or newer (1.1.1 is what I used).

It appears that the most significant change is https://github.com/google/snappy/commit/27a0cc394950ebdad2e8d67322f0862835b10bd9, where the block size was changed from 32k to 64k.

**Comment by bokken** [comment]
That does appear to be the only change. I made the corresponding change in my fork to the SnappyCompressor. It also required changing the encoding hash table to be changed from a short[] to an int[]. At that point the byte for byte tests compared to xerial's snappy-java 1.1.1 pass (as do all the other unit tests).

**Comment by dain** [comment]
I have a branch somewhere where I integrated all the changes, but got busy and never merged it.

**Comment by bokken** [comment]
Is there any chance of #27 getting pulled in? That pull request includes the changes to be byte compatible with snappy 1.1.

**Comment by dain** [comment]
@bokken we have moved all development to https://github.com/airlift/aircompressor, which supports Snappy, LZ4 and LZO and includes Hadoop codec implementations for all of these.  Unfortunately, I clearly don't have the time to work on this fork anymore. If you find issues with those implementations, please file an issue over there.
