### ISSUE TITLE
when will 0.4 release?

### ISSUE THREAD

**Issue by majingshan** [dain/snappy#29]
I need a released version for maven dependency, so is there a eta or something that 0.4 will be released.

**Comment by dgavrus** [comment]
Hello, I need a released version too. I see changes in IO classes and I would like to use new version (0.4),  but after changes were made there was no version bump :(

**Comment by dain** [comment]
I just released 0.4 (https://repo1.maven.org/maven2/org/iq80/snappy/snappy/0.4/).  Let me know is there are any problems.
