### ISSUE TITLE
Exception in Snappy.determineSnappyInputStream

### ISSUE THREAD

**Issue by jeffxi** [dain/snappy#34]
in version 0.4, Snappy.Java line 62. 

if (read != STREAM_HEADER.length || read != HEADER_BYTES.length) {
           throw new IllegalArgumentException("invalid header");
 }

Is the logic valid? The condition will always be false so I always get an exception.

Should it be:

if (read != STREAM_HEADER.length && read != HEADER_BYTES.length) {
           throw new IllegalArgumentException("invalid header");
 }

**Comment by dain** [comment]
Ya that is totally wrong.  We have moved future development to https://github.com/airlift/aircompressor

But I'll fix this here also
