### ISSUE TITLE
Does not work with SequenceFile

### ISSUE THREAD

**Issue by sertel** [dain/snappy#36]
Hi,

the codec does not work with the SequenceFile format, which is one of the most widely used file formats in Hadoop. That's a pity because I like the idea of not having to link a native library.

That being said, I forked your repo and will commit the changes that are necessary in order to make it work for SequenceFile. I can also provide a test case that shows that it is working for SequenceFile.

Sadly, your regression is failing because I disabled the following two things:

1. No more guessing on when the input stream finishes. (eof flag)
2. The stream header does not work in the context of Hadoop. I looked into the native implementation of Snappy and could not find where they are doing that. Is this really required?

Can you please comment on that and let me know what would be your take on that?

Cheers,
Sebastian.

**Comment by dain** [comment]
@sertel we have moved all development to https://github.com/airlift/aircompressor, which supports Snappy, LZ4 and LZO and includes Hadoop codec implementations for all of these.  If you find issues with those implementations, please file an issue over there.

**Comment by sertel** [comment]
This is perfect, thanks a lot for that pointer! (Should be on the top of the page for this project.)
