### ISSUE TITLE
Stream format without requiring streams

### ISSUE THREAD

**Issue by ijuma** [dain/snappy#4]
As far as I understand, there is no way to get the stream format without using streams. In Voldemort, we have the data in a byte[] and it's wasteful to use a stream for the compression step.

At the same time, it would be nice to add a checksum and potentially avoid compression for cases where it doesn't help (like the stream format does). It's not too much work to do it manually, but it would be great if it was available as an out of the box method.

**Comment by dain** [comment]
This repository has been migrated to https://github.com/airlift/aircompressor/.  Please test using the latest aircompressor and post there if it is still an issue.
